settings:
  #:server: irc.twitch.tv
  :server: irc.rizon.net
  :channels:
     - '#/g/bots'
     - '#touku'
    #- '#kurufu2'
  :nick: DefNotKubot2
  #:password: 'oauth:b3dfy82v3sqzi4kdn2mbck77pmwn0e'
  :plugins:
    :plugins:
      - SimpleFaq
      - CurrentTime
      #- StreamSchedule
      #- QuoteDB
      - Bonus
    :options:
      SimpleFaq:
        :FileName: faq.yml

whitelist:
  - bob
admins:
  - kurufu
